# frozen_string_literal: true

# E11y configuration — generated by `rails g e11y:install`
# Docs: https://github.com/arturseletskiy/e11y

E11y.configure do |config|
  # Minimal setup: stdout adapter (events print to console).
  # Add Loki, Sentry, etc. when ready — see docs for adapter config.
  config.adapters[:logs] = E11y::Adapters::Stdout.new(colorize: true)

  # Optional: uncomment to add more adapters
  # config.adapters[:errors_tracker] = E11y::Adapters::Sentry.new(dsn: ENV["SENTRY_DSN"])
  # config.adapters[:logs] = E11y::Adapters::Loki.new(url: ENV.fetch("LOKI_URL", "http://localhost:3100"))
end
