# frozen_string_literal: true

# E11y configuration — generated by `rails g e11y:install`
#
# Full documentation: https://github.com/your-org/e11y
# Quick Start:        docs/QUICK-START.md

E11y.configure do |config|
  # ─── Service identity ────────────────────────────────────────────────────────
  # config.service_name = Rails.application.class.module_parent_name.underscore
  # config.environment  = Rails.env.to_s

  # ─── Adapters ────────────────────────────────────────────────────────────────
  # Register adapter instances by logical name.
  # The same name is referenced from event classes via `adapters :logs`.
  #
  # config.adapters[:logs] = E11y::Adapters::Loki.new(
  #   url: ENV.fetch("LOKI_URL", "http://localhost:3100")
  # )
  # config.adapters[:errors_tracker] = E11y::Adapters::Sentry.new(
  #   dsn: ENV["SENTRY_DSN"]
  # )
  #
  # Development / test: use the null adapter (silent, inspectable)
  # config.adapters[:logs] = E11y::Adapters::NullAdapter.new

  # ─── Request-scoped debug buffering ──────────────────────────────────────────
  # Debug events are buffered per-request and flushed only when a 5xx error occurs.
  #
  # config.ephemeral_buffer.enabled = true

  # ─── PII filtering ───────────────────────────────────────────────────────────
  # Define per-event via pii_filtering do ... end in event classes.
  # Use inheritance: BaseUserEvent with common rules, child events add/override.

  # ─── Rate limiting ───────────────────────────────────────────────────────────
  # config.rate_limiting do
  #   global limit: 10_000, window: 1.0   # 10K events/sec globally
  #   per_event "user.login.failed", limit: 100, window: 60.0
  # end

  # ─── SLO tracking ────────────────────────────────────────────────────────────
  # config.slo do
  #   http_ignore_statuses [404, 401]
  #   latency_percentiles  [50, 95, 99]
  # end

  # ─── Cardinality protection ───────────────────────────────────────────────────
  # config.cardinality_protection do
  #   max_cardinality 1000
  # end
end

# Call E11y.start! to initialise adapters after configuration.
# In Rails this is handled automatically by the Railtie.
